name: CI-CD for Data Quality
on:
  push:
    branches: [deployment, fa_backend]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Install OpenVpn
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openvpn

      - name: Set up OpenVpn
        env:
          OVPN_FILE: ${{ secrets.OVPN_FILE }}
        run: |
          echo "$OVPN_FILE" > openvpn-config.ovpn
          sudo chmod 600 openvpn-config.ovpn
          sudo openvpn --config openvpn-config.ovpn
          echo "Status is $?"
          sleep 10
          ps -ef | grep -i openvpn
        
      - name: Execute Custom commands
        env:
          SSH_PVT_KEY: ${{ secrets.EC2_PVT_KEY }}
          EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$EC2_PVT_KEY" > key.pem
          chmod 400 key.pem
          
          ssh -i key.pem $EC2_USER@$EC2_IP << 'EOF'
          cd /home/shashank_daaslabs/OD_DB_Files
          touch test_file.txt
          EOF

