name: CI-CD for Data Quality
on:
  push:
    branches: [deployment, fa_backend]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Install OpenVpn
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Set up OpenVpn
        env:
          OVPN_FILE: ${{ secrets.OVPN_FILE }}
        run: |
          echo "$OVPN_FILE" > openvpn-config.ovpn
          sudo chmod 400 openvpn-config.ovpn
          sudo openvpn --config openvpn-config.ovpn --daemon
        
      - name: Wait for VPN Connection
        run: |
          sleep 10
        
      - name: Execute Custom command
        env:
          SSH_PVT_KEY: ${{ secrets.EC2_PVT_KEY }}
          EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
          ec2_user: ${{ secrets.SSH_USER }}
        run: |
          echo "$EC2_PVT_KEY" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem -n $ec2_user@$EC2_IP << 'EOF'
          cd /home/shashank_daaslabs/OD_DB_Files
          touch test_file.txt
          EOF

