name: CI-CD for Data Quality
on:
  push:
    branches: [deployment, fa_backend]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ssh-agent-deploy-key
        uses: Sithi5/remote-ssh-commands-action@main
        with:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.EC2_PVT_KEY }}
            SSH_HOST: ${{ secrets.EC2_PUBLIC_IP }}
            SSH_PORT: 22
            SSH_REMOTE_COMMANDS: cd /home/shashank_daaslabs/Downloads;touch test.txt
            